spring:
  datasource:
    dynamic:
      primary: mysql #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        sqlserver:
          username: test
          password: quickdev789
          url: jdbc:sqlserver://111.198.53.100:30031;DatabaseName=JCRLZS
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        mysql:
          username: root
          password: root
          url: jdbc:mysql://localhost/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
