app:
  host: "localhost"
  #  host-prefix: "http://${app.host}:${server.port}/file/getImage/"
  host-prefix: "/file/getImage/"
  #  windows环境时配置此项作为图片存放路径
  windows-file-location: "C:\\Users\\84271\\Desktop\\实习\\images\\"
  #  linux下配置此项作为图片存放路径
  linux-file-location: "./images/"
spring:
  application:
    name: demo
    #    图片基础路径
    imagePrefix: "image:"
  #mvc接收参数时对日期进行格式化
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  thymeleaf:
    mode: HTML
    cache: false
  profiles:
    active: prop
  mvc:
    format:
      date: yyyy-MM-dd
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080