spring:
  application:
    name: demo
  #mvc接收参数时对日期进行格式化
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  thymeleaf:
    mode: HTML
    cache: false
  profiles:
    active: prop
  mvc:
    format:
      date: yyyy-MM-dd
mybatis:
  configuration:
    map-underscore-to-camel-case: true